version: '2'
services:
  mock-server:
    image: rodolpheche/wiremock
    ports:
     - "8080:8080"
    volumes:
     - ./mappings:/home/wiremock/mappings
     - ./__files:/home/wiremock/__files
    command: |
      --verbose
     
